WebIDL requires calls with too few arguments to throw a TypeError exception, so the test suite should not fail if you do. We have previously agreed not to test this in the conformance tests, so removing the tests with too few parameters.